---
  execution:
    iterations: 50
    concurrency: 5
    scenario: with_script

  scenarios:
    with_script:
      script: ../script/TestC2.jmx

  reporting:
    module: final-stats
    summary: true  # overall samples count and percent of failures
    percentiles: true  # display average times and percentiles
    failed-labels: false  # provides list of sample labels with failures
    test-duration: true  # provides test duration
    dump-csv: perf_result_csv.csv