---
  execution:
    - iterations: 50
      concurrency: 5
      scenario: with_script
    - iterations: 1
      concurrency: 2
      scenario: seq_exe

  scenarios:
    with_script:
      script: ../script/TestC2.jmx
    seq_exe:
      script: ../script/OneLoginMultipleAction.jmx

  modules:
    blazemeter:
      token: 16d16ddc4d4fc12738562fb3:88fe44bb074a3181ca8c21ed0704b9fb4d1a09b26c73dbe8c25412c400872057f3b310cf

  reporting:
    - module: console
    - module: final-stats
      summary: true
      percentiles: true
      failed-labels: false
      test-duration: true
      dump-csv: TaurusResult/perf_result_csv.csv
    - module: blazemeter
      report-name: Taurus test report
      test: Taurus test
      project: Taurus test project

  settings:
    artifacts-dir: TaurusResult